package CorbaChat;


/**
* CorbaChat/CorbaServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Wednesday, December 19, 2018 6:46:32 AM CST
*/

abstract public class CorbaServerHelper
{
  private static String  _id = "IDL:CorbaChat/CorbaServer:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaChat.CorbaServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaChat.CorbaServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CorbaChat.CorbaServerHelper.id (), "CorbaServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaChat.CorbaServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CorbaServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaChat.CorbaServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CorbaChat.CorbaServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaChat.CorbaServer)
      return (CorbaChat.CorbaServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaChat._CorbaServerStub stub = new CorbaChat._CorbaServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CorbaChat.CorbaServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaChat.CorbaServer)
      return (CorbaChat.CorbaServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaChat._CorbaServerStub stub = new CorbaChat._CorbaServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
