package CorbaChat;

/**
* CorbaChat/CorbaServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Wednesday, December 19, 2018 6:46:32 AM CST
*/

public final class CorbaServerHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaChat.CorbaServer value = null;

  public CorbaServerHolder ()
  {
  }

  public CorbaServerHolder (CorbaChat.CorbaServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaChat.CorbaServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaChat.CorbaServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaChat.CorbaServerHelper.type ();
  }

}
