package CorbaChat;


/**
* CorbaChat/CorbaServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Wednesday, December 19, 2018 6:46:32 AM CST
*/

public interface CorbaServer extends CorbaServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaServer
