package CorbaChat;


/**
* CorbaChat/CorbaServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServer.idl
* Wednesday, December 19, 2018 6:46:32 AM CST
*/

public abstract class CorbaServerPOA extends org.omg.PortableServer.Servant
 implements CorbaChat.CorbaServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("create", new java.lang.Integer (0));
    _methods.put ("list", new java.lang.Integer (1));
    _methods.put ("join", new java.lang.Integer (2));
    _methods.put ("leave", new java.lang.Integer (3));
    _methods.put ("writeMessage", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CorbaChat/CorbaServer/create
       {
         String room = in.read_string ();
         String user = in.read_string ();
         this.create (room, user);
         out = $rh.createReply();
         break;
       }

       case 1:  // CorbaChat/CorbaServer/list
       {
         String $result = null;
         $result = this.list ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // CorbaChat/CorbaServer/join
       {
         String room = in.read_string ();
         String user = in.read_string ();
         String $result = null;
         $result = this.join (room, user);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // CorbaChat/CorbaServer/leave
       {
         String room = in.read_string ();
         String user = in.read_string ();
         String $result = null;
         $result = this.leave (room, user);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // CorbaChat/CorbaServer/writeMessage
       {
         String msg = in.read_string ();
         String room = in.read_string ();
         String user = in.read_string ();
         String $result = null;
         $result = this.writeMessage (msg, room, user);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaChat/CorbaServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CorbaServer _this() 
  {
    return CorbaServerHelper.narrow(
    super._this_object());
  }

  public CorbaServer _this(org.omg.CORBA.ORB orb) 
  {
    return CorbaServerHelper.narrow(
    super._this_object(orb));
  }


} // class CorbaServerPOA
